# Generated by Django 5.2 on 2025-04-08 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_medicalrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='available_time_end',
            field=models.TimeField(default=''),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='available_time_start',
            field=models.TimeField(default=''),
        ),
        migrations.AlterField(
            model_name='patient',
            name='age',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
