# Generated by Django 5.2 on 2025-04-09 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_doctor_available_time_end_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='available_time_end',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='available_time_start',
        ),
        migrations.AlterField(
            model_name='doctor',
            name='available_days',
            field=models.JSONField(default=dict),
        ),
    ]
