databases:
  - name: campaign
    plan: free
    databaseName: tiberbu
    user: tiberbu

services:
  - type: web
    plan: free
    name: healthcare
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn backend.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: campaign_kzcd
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
